//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: Message.proto

package com.example.demo.grpc.proto;

@kotlin.jvm.JvmName("-initializemessageResponse")
inline fun messageResponse(block: com.example.demo.grpc.proto.MessageResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.Message.MessageResponse =
  com.example.demo.grpc.proto.MessageResponseKt.Dsl._create(com.example.demo.grpc.proto.Message.MessageResponse.newBuilder()).apply { block() }._build()
object MessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.demo.grpc.proto.Message.MessageResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.proto.Message.MessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.proto.Message.MessageResponse = _builder.build()

    /**
     * <code>bool success = 1;</code>
     */
    var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * <code>bool success = 1;</code>
     */
    fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * <code>string message = 2;</code>
     */
    var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 2;</code>
     */
    fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.example.demo.grpc.proto.Message.MessageResponse.copy(block: com.example.demo.grpc.proto.MessageResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.Message.MessageResponse =
  com.example.demo.grpc.proto.MessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

