//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: Message.proto

package com.example.demo.grpc.proto;

@kotlin.jvm.JvmName("-initializemessageRequest")
inline fun messageRequest(block: com.example.demo.grpc.proto.MessageRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.Message.MessageRequest =
  com.example.demo.grpc.proto.MessageRequestKt.Dsl._create(com.example.demo.grpc.proto.Message.MessageRequest.newBuilder()).apply { block() }._build()
object MessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.demo.grpc.proto.Message.MessageRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.proto.Message.MessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.proto.Message.MessageRequest = _builder.build()

    /**
     * <code>string sender = 1;</code>
     */
    var sender: kotlin.String
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * <code>string sender = 1;</code>
     */
    fun clearSender() {
      _builder.clearSender()
    }

    /**
     * <code>string receiver = 2;</code>
     */
    var receiver: kotlin.String
      @JvmName("getReceiver")
      get() = _builder.getReceiver()
      @JvmName("setReceiver")
      set(value) {
        _builder.setReceiver(value)
      }
    /**
     * <code>string receiver = 2;</code>
     */
    fun clearReceiver() {
      _builder.clearReceiver()
    }

    /**
     * <code>string content = 3;</code>
     */
    var content: kotlin.String
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <code>string content = 3;</code>
     */
    fun clearContent() {
      _builder.clearContent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.example.demo.grpc.proto.Message.MessageRequest.copy(block: com.example.demo.grpc.proto.MessageRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.Message.MessageRequest =
  com.example.demo.grpc.proto.MessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

