spring:
  application:
    name: spring-cloud-dubbo-consumer
  #  config:
  #    import: optional:zookeeper
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    zookeeper:
      discovery:
        register: true
        root: services/spring-cloud
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://localhost:2181
#  config-center:
#    address: ${dubbo.registry.address}
##  monitor:
##    address: ${dubbo.registry.address}
#  metadata-report:
server:
  port: 9091
#    address: ${dubbo.registry.address}
logging:
  level:
    org.apache.dubbo: debug
    web: debug