//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: UserService.proto

package com.example.demo.grpc.proto.user;

@kotlin.jvm.JvmName("-initializeuserAddRequest")
inline fun userAddRequest(block: com.example.demo.grpc.proto.user.UserAddRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.user.UserService.UserAddRequest =
  com.example.demo.grpc.proto.user.UserAddRequestKt.Dsl._create(com.example.demo.grpc.proto.user.UserService.UserAddRequest.newBuilder()).apply { block() }._build()
object UserAddRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.demo.grpc.proto.user.UserService.UserAddRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.proto.user.UserService.UserAddRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.proto.user.UserService.UserAddRequest = _builder.build()

    /**
     * <code>string username = 1;</code>
     */
    var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * <code>string username = 1;</code>
     */
    fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * <code>string password = 2;</code>
     */
    var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * <code>string password = 2;</code>
     */
    fun clearPassword() {
      _builder.clearPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.example.demo.grpc.proto.user.UserService.UserAddRequest.copy(block: com.example.demo.grpc.proto.user.UserAddRequestKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.user.UserService.UserAddRequest =
  com.example.demo.grpc.proto.user.UserAddRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

