//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: UserService.proto

package com.example.demo.grpc.proto.user;

@kotlin.jvm.JvmName("-initializeuserResponse")
inline fun userResponse(block: com.example.demo.grpc.proto.user.UserResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.user.UserService.UserResponse =
  com.example.demo.grpc.proto.user.UserResponseKt.Dsl._create(com.example.demo.grpc.proto.user.UserService.UserResponse.newBuilder()).apply { block() }._build()
object UserResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.demo.grpc.proto.user.UserService.UserResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.demo.grpc.proto.user.UserService.UserResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.demo.grpc.proto.user.UserService.UserResponse = _builder.build()

    /**
     * <code>int32 status = 1;</code>
     */
    var status: kotlin.Int
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>int32 status = 1;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * <code>string result = 2;</code>
     */
    var result: kotlin.String
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>string result = 2;</code>
     */
    fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.example.demo.grpc.proto.user.UserService.UserResponse.copy(block: com.example.demo.grpc.proto.user.UserResponseKt.Dsl.() -> kotlin.Unit): com.example.demo.grpc.proto.user.UserService.UserResponse =
  com.example.demo.grpc.proto.user.UserResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

